# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Display the path
      shell: bash
      run: echo $PATH
    - name: Clean temp directory
      working-directory: ./src/frontend
      shell: bash
      run: echo 'pwd'
    - run: npm ci
    - run: npm run build --if-present