# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #call-workflow-local:
   # uses: ./.github/workflows/CI_test.yml
    
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/frontend

    steps:
    - name: check out the respository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install dependencies
      run: npm ci

    - name: build the project
      run: npm run build

    - name: List files in build directory
      run: ls -la build/

    - name: Archive build artifacts
      run: |
        mkdir -p artifacts
        cp -R build/* artifacts/

    - name: List files in artifacts directory after copying
      run: ls -la artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build-artifacts
        path: artifacts/

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build-artifacts

      - name: List downloaded files
        run: ls -la ./artifacts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifacts
          publish_branch: main 