# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: action temp

on: 
  workflow_call:
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: temp 1
      run: echo temp